### ISSUE TITLE
0.1.12d roadmap

### ISSUE THREAD

**Issue by samhocevar** [samhocevar/zepto8#10]
PICO-8 v0.1.12d Candidate Changelog 2020-03-15

 - [x] Added: 8-bit character set with kana, alt font
 - ~~Added: SFX / Pattern organiser view~~
 - ~~Added: SFX edit buttons on pattern channels~~
 - [x] Added: ord(), chr()
 - [ ] Added: SPLORE automatically updates BBS carts when online
 - [ ] Added: Search for similar (shared tags) cartridges, by thread, or by revision history
 - [x] Added: predefined fillp() pattern values assigned to glyphs
 - [ ] Added: __tostring metatable method observed by tostr() / print() / printh()
 - [x] Added: btnp() custom delays
 - [ ] Added: "." shorthand command for advancing a single frame (calls _update, _draw if they exist)
 - ~~Added: Current editor/cart view is recorded every 3 seconds to [app_data]/activity_log.txt~~
 - ~~Added: Cutting (ctrl-x) and pasting selected sprites while in map view to also adjust map references to those sprites~~
 - [ ] Added: Clipboard is supported in the html exports (with a few limitations) // load #wobblepaint for an example.
 - [ ] Added: Can load .lua files as cartridges
 - [x] Added: Unary operators: ..= ^=
 - [ ] Added: New and updated demo carts: waves.p8 dots3d.p8 auto2d.p8 wander.p8 cast.p8 jelpi.p8 (use INSTALL_DEMOS)
 - [ ] Added: Pre-installed games: Gar's Den, 8 Legs to Love (use INSTALL_GAMES)
 - [ ] Added: Splore cart labels for .p8 files
 - ~~Added: Now 16 code tabs (click on the rightmost ones to scroll)~~
 - [x] Added: ipairs()
 - [ ] Added: SAVE from commandline to quick-save current cartridge (same as ctrl-s)
 - [ ] Added: BACKUP from commandline to save a backup of current cartridge
 - [ ] Added: CPU usage widget (ctrl-p while running cartridge)
 - [x] Added: Button / dpad states exposed in memory at 0x5f4c
 - ~~Added: pico8_dyn version is included when exporting to Raspberry Pi~~
 - ~~Improved: HTML exports run smoother (miscellaneous optimisations and html shell adjustments)~~
 - ~~Improved: Lower cpu usage for small foreground_sleep_ms values (changed host event loop & fps switching strategy)~~
 - [x] Changed: line() or line(col) can be used to skip drawing and set the (line_x1, line_y1) state on the next call to line(x1,y1)
 - [ ] Changed: api functions can only be overwritten during cartridge execution
 - [ ] Changed: sqrt(x) is now more accurate, and a little faster than x^.5
 - [ ] Changed: sqrt(x) returns 0 for negative values of x
 - [x] Changed: btnp() delay and repeats now work independently per-button
 - [ ] Changed: pairs(nil) returns an empty
 - [ ] Changed: Default screenshot scale (now 4x), gif scale (now 3x)
 - [ ] Changed: gif_len now means the length when no start point is specified (used to be the maximum recordable length)
 - [ ] Changed: (Multicarts) When loading data from many different carts, the swap delay maxes out at ~2 seconds
 - ~~Changed: (Raspberry Pi) removed support for (and dependency on) libsndio~~
 - [x] Changed: camera(), cursor(), color(), pal(), palt(), fillp(), clip() return their previous state
 - [ ] Changed: can not call folder() from a BBS cart running under splore
 - [x] Changed: rnd(-x) returns -rnd(x)
 - [ ] Changed: F9 resets the video, so that multiple presses results in a sequence of clips that can be joined to together
 - [x] Changed: color() defaults to 6 (was 0)
 - [ ] Changed: Backed up file's name's are prefixed with a timestamp.
 - [ ] Changed: Automatically start on the (host's) current path if it is inside PICO-8's root path
 - [x] Changed: tostr(x,true) can also be used to view the hex value of functions and tables (uses Lua's tostring)
 - ~~Fixed: Mac OSX keyboard permissions (fixed in SDL2 0.2.10)~~
 - [ ] Fixed: Audio mixer: SFX with loop_end > 32 would sometimes fail to loop back
 - [ ] Fixed: print("foo",64,64) print("hoge") prints both on the same line
 - [ ] Fixed: btn() firing a frame late, and not on the same frame as stat(30)
 - [ ] Fixed: #include can not handle files saved by some Windows text editors in default format (w/ BOM / CRLF)
 - [ ] Fixed: Exports do not flatten #include'd files
 - ~~Fixed: Copying and pasting music copies references to SFX instruments without copying the SFX instrument~~
 - [ ] Fixed: Preprocessor fails when multiple shorthand expressions + strings containing brackets appear on the same line
 - [ ] Fixed: Default window size has too much black border (now reverted to previous default)
 - [ ] Fixed: Functions yielded inbetween frames occasionally push an extra return value (type:function) to the stack
 - [ ] Fixed: can't load png-encoded carts with code that starts with a :
 - ~~Fixed: gif output unnecessarily large~~
 - [ ] Fixed: gif recording skipping frames when running at 15fps
 - [ ] Fixed: printh does not convert to unicode when writing to console or to a file
 - ~~Fixed: cart data sometimes not flushed when loading another cart during runtime~~
 - ~~Fixed: Can not navigate patterns with -,+ during music playback~~
 - ~~Fixed: Mouse cursor not a hand over some buttons~~
 - ~~Fixed: Laggy mouseover messages (e.g. showing current colour index, or map coordinates)~~
 - ~~Fixed: Can't paste glyphs into search field~~
 - ~~Fixed: Tab spacing always jumps config.tab_spaces instead of snapping to next column~~
 - ~~Fixed: -p switch name is wrong (was only accepting "-param" in 0.12.*~~
 - ~~Fixed: Code editor highlighting goes out of sync after some operations~~
 - [ ] Fixed: Multicart communication problem (affecting PICOWARE)
 - [ ] Fixed: time() speeds up after using the RESUME command
 - [ ] Fixed: Audio state is clobbered when using the RESUME command
 - [ ] Fixed: Audio glitch when fading out music containing slide effect (1)
 - [ ] Fixed: Toggling sound from splore cart->options menu has no effect
 - [ ] Fixed: Devkit keyboard works when paused
 - [ ] Fixed: Weird behavior of -32768 % y
 - ~~Fixed: Replacing all text in code editor breaks undo history~~
 - ~~Fixed: double click to select last word in code does not include the last character~~
 - ~~Fixed: weird block comment behavior in code editor~~
 - ~~Fixed: Exported html cart names can not contain quotes~~
 - [ ] Fixed: LOAD("#ABC") does not always immediately yield
 - [ ] Fixed: Infinite RUN() loop crashes PICO-8
 - ~~Fixed: Mouse cursor is not a finger on top of most "pressable" button-style elements~~
 - [ ] Fixed: CD command fails when root_path is relative (e.g. "pico8 -root_path .")
 - [x] Fixed: poke in fill pattern addresses (0x5f31..0x5f33) discards some bits
 - ~~Fixed: After using ctrl-click in map editor, can not modify map outside that region~~
 - ~~Fixed: Shift-selecting sprites from bottom right to top left selects wrong region~~
 - [ ] Fixed: Changing GIF_LEN from PICO-8 commandline sometimes breaks gif saving
 - [x] Fixed: pget() sometimes returns values with high bits set
 - [x] Fixed: preprocessor: unary operator lhs is not separated in some cases (e.g. x=1y+=1)
 - [x] Fixed: preprocessor: ? shorthand prevents other preprocess replacements on same line
 - ~~Fixed: Loading a .p8 file with too many tabs discards the excess code.~~
 - ~~Fixed: Map editor's stamp tool wraps around when stamping overlapping the right edge.~~
 - [ ] Fixed: Very quick/light tap events sometimes do not register

**Comment by samhocevar** [comment]
This is rendered obsolete by #11.
