### ISSUE TITLE
PICO-8 v0.2.0b compatiblity roadmap

### ISSUE THREAD

**Issue by samhocevar** [samhocevar/zepto8#12]
- [ ] Changed: #include directive can be preceeded by whitespace
 - [ ] Changed: Activity logger records nothing after idle for 30 seconds
 - [ ] Fixed: Mouse cursor movement in editor is not smooth
 - [ ] Fixed: Screen palette doesn't reset after exiting splore
 - [ ] Fixed: PALT() returns 0 instead of previous state as bitfield
 - [ ] Fixed: Rectangle and line tools broken when used in map editor
 - [ ] Fixed: INSTALL_GAMES under Windows produces broken cart files
 - [ ] Fixed: Stored multicart sometimes has code section truncated (fails to load())
