### ISSUE TITLE
PICO-8 v0.2.0d compatiblity roadmap

### ISSUE THREAD

**Issue by samhocevar** [samhocevar/zepto8#14]
- [ ] Added: rnd(x) when x is an array-style table, returns a random item from that table
 - [ ] Added: gif_reset_mode (in config.txt / CONFIG command). Defaults to 0.1.12c behaviour
 - [ ] Added: print(str, col) form behaves the same as: color(col) print(str)
 - [ ] Added: Operators: <<> >>< <<>= >><=
 - [ ] Changed: tline now also observes an offset (0x5f3a, 0x5f3b)
 - [ ] Changed: tline rounds down to integer screen coordinates (same as line)
 - [ ] Changed: Final cpu adjustments (see release post)
 - [ ] Changed: Removed experimental "!"->"this" shorthand
 - [ ] Changed: clip() returns previous state as 4 return values
 - [ ] Fixed: Included files remain locked (and can not be edited by external editors)
 - [ ] Fixed: Carts loaded as plaintext .lua fail to handle BOM / DOS characters
 - [ ] Fixed: palt() returns previous state of bitfield as a boolean instead of a number
 - [ ] Fixed: CPU speed on widget doesn't exactly match stat(1)
 - [ ] Fixed: stat(1) occasionally reports garbage values when above 1.0
 - [ ] Fixed: Custom btnp repeat rates (0x5f5c, 0x5f5d) speed up when skipping frames
 - [ ] Fixed: gif_scale setting not read from config.txt
 - [ ] Fixed: tline: texture references are incorrect when sy1 < sy0
 - [ ] Fixed: tline: single pixel spans are drawn as two pixels
 - [ ] Fixed: binary exports' controls menu always shows 0 joyticks connected
 - [ ] Fixed: Pressing DEL on first row of tracker doesn't do anything
 - [ ] Fixed: host framerate regulation is slow (~1/sec) when PICO-8 frame takes < 1ms to execute
 - [ ] Fixed: fillp() return value (previous state) does not include transparency bit
 - [ ] Fixed: clip"" setting all clip values to 0 (should be ignored)
 - [ ] Fixed: Raspberry Pi static build / static export requires GLIBC 2.0.29 (now .16)
 - [ ] Fixed: stop(nil) crashes
 - [ ] Fixed: print(), printh(), stop() prints "nil" with no arguments (should have no output)
 - [ ] Fixed: trace() can not be used with coroutines
