### ISSUE TITLE
PICO-8 v0.2.0e compatiblity roadmap

### ISSUE THREAD

**Issue by samhocevar** [samhocevar/zepto8#16]
- ~~Added: zip file creation (with preserved file attributes) when exporting binaries~~
 - [ ] Added: cpu working animation when cpu usage > 120 skipped frames
 - [ ] Improved: stop() / resume now works at the instruction level
 - ~~Fixed: tline clipping broken (from 0.2.0d)~~
 - [ ] Fixed: cpu counting is wrong inside coroutines
 - [ ] Fixed: coroutines interrupted by garbage collection
 - [ ] Fixed: code compression suddenly much worse for carts > 32k chars
 - ~~Fixed: code compression ratio can be less than 1 in extreme cases~~
 - ~~Fixed: pasting a string ending in '1' into the command prompt opens the editor~~
 - ~~Fixed: html export can run out of pre-allocated heap when doing heavy string operations~~
 - [ ] Fixed: hex memory addresses displayed in puny font on windows
 - ~~Fixed: devkit mouse message shown once per cart -- should be once per chain of carts~~
 - ~~Fixed: can't paste sfx notes after moving to another sfx via keyboard~~
 - ~~Fixed: copying note select vs. sfx vs. pattern range is ambiguous~~
 - [ ] Fixed: crash after redefining type()
