### ISSUE TITLE
PICO-8 v0.2.0f compatiblity roadmap

### ISSUE THREAD

**Issue by samhocevar** [samhocevar/zepto8#17]
- [x] Changed: @@ operator (peek2) to %
 - ~~Fixed: Exported wasm crashes on boot when code contains a numerical constant out of range.~~
 - ~~Fixed: HTML Shell treats controller shoulder buttons as MENU; easy to accidentally bump.~~
 - [x] Fixed: shift operators behaviour undefined for negative values of n (now: x << n means x >> -(n\1))
 - [x] Fixed: >>> operator behaviour does not match lshr(a,b) when b >= 32
 - [x] Fixed: INFO crashes when code is close to 64k of random characters
 - ~~Fixed: Code editor undo step not stored when starting to edit a new line (hard to see what happened)~~

**Comment by gamax92** [comment]
Numerical literals in code higher that ~32767.9999 or lower than -32768 no longer get clamped to -32768 since v0.2.0f

0.2.0f writes carts with a version of 24 while 0.2.0e writes a version of 23, if backwards compatibility is desired, not that 0.2.0f implements anything like that.

**Comment by samhocevar** [comment]
Thanks for the additional tips. Both issues are fixed in 56ce847b74b4c17493f8999f3186e49d15c6ded6 and I also think this issue can be closed.
