### ISSUE TITLE
PICO-8 v0.2.0g compatiblity roadmap

### ISSUE THREAD

**Issue by samhocevar** [samhocevar/zepto8#18]
- ~~Added: Window title shows current cartridge filename while editing~~
 - [ ] Changed: ~ preceeding a numerical constant (e.g. ~1) counts as a single token
 - [ ] Fixed: >>> operator behaviour does not match lshr(a,b) when b >= 32 (again)
 - [ ] Fixed: PICO-8 freezes when shift by -0x8000
 - [ ] Fixed: .p8 format does not store extpal label colours
 - ~~Fixed: Can not save screenshot when filename contains ":"~~
