### ISSUE TITLE
PICO-8 v0.2.0h compatiblity roadmap

### ISSUE THREAD

**Issue by samhocevar** [samhocevar/zepto8#19]
- [ ] Added: tline() takes an optional layers parameter, similar to map()
 - [ ] Added: high bits of 0x5f5e taken as colour read mask, low taken to be colour write mask
 - ~~Added: Double-click in the sfx tracker to select all attributes of a single note.~~
 - [ ] Fixed: assignment shorthand RHS scope wrong when contains certain operators. e.g. a+=1&127
 - [ ] Fixed: while/if shorthands fail when "do" or "then" appears on the same line as part of an identifier
 - ~~Fixed: ctrl-c copies the wrong sfx after clicking pencil button (next to pattern #) in organiser view~~
 - ~~Fixed: spinning cart icon present in video memory when cart boots from splore~~
