### ISSUE TITLE
PICO-8 v0.2.0i compatiblity roadmap

### ISSUE THREAD

**Issue by samhocevar** [samhocevar/zepto8#20]
- [ ] Added: pack(), unpack()
 - [ ] Changed: bitplane read/write mask only reset after finished running program
 - [ ] Fixed: tline() doesn't draw anything when the layers argument is not given
