### ISSUE TITLE
PICO-8 v0.2.1 compatiblity roadmap

### ISSUE THREAD

**Issue by samhocevar** [samhocevar/zepto8#22]
- [x] Added: oval() ovalfill()
 - [ ] Added: circle drawing tool is now an oval tool (hold shift for circle)
 - ~~Added: hold shift with line tool to snap to 22.5 degree angles from origin (0:1, 1:1, 2:1 gradients)~~
 - [ ] Added: serial() channels for stdin, stdout
 - [ ] Added: raw binary and image files dropped in to PICO-8 also become byte streams readable w/ serial()
 - [ ] Added: add(tbl, val, index) -- insert val into table at index
 - [ ] Added: deli(tbl, index) -- delete element from table by index (index defaults to last element)
 - ~~Added: show progress while exporting binaries (can be slow now that generating zip files)~~
 - [ ] Added: -e to add an extra file to exported binaries zip files // export -e manual.txt foo.bin
 - [ ] Added: RESET command to reset the runtime / draw state
 - [ ] Added: drag and drop cartridges into PICO-8 window to load them
 - [ ] Added: hash stored in .p8.png so that cartridges corrupted by image quantization can show a specific error
 - [x] Added: raw data blocks in compressed code format (useful for storing long binary strings efficiently)
 - [ ] Added: clip(x,y,w,h,true): 5th parameter indicates that the clipping region should be clipped by the old one
 - [ ] Added: -export switch can be used to convert .p8 files and .p8.png fromm commandline. // pico8 foo.p8 -export foo.p8.png
 - ~~Changed: all drawing operations in sprite editor now observe fill pattern state~~
 - [ ] Changed: numbers can be immediately followed by identifiers (a=1b=2) // lexaloffle.com/bbs/?tid=38638
 - [ ] Changed: line(),rect() cost the same as rectfill() when drawing equivalent shapes
 - ~~Changed: Sprite editor shows only active area after shift-selecting sprites~~
 - ~~Changed: copy/paste in the code editor treats uppercase ascii characters as puny font only when puny mode (ctrl+p) enabled~~
 - [ ] Changed: C0 Controls characters (except for 0x0,0x9,0xa,0xd) encoded in .p8 / clipboard with unicode replacements
 - [ ] Changed: serial() returns number of bytes processed (1/8ths included for partial bytes)
 - ~~Improved: exported binary's data.pod file 96% smaller (~870k -> ~85k)~~
 - [ ] Fixed: pack(...).n is shifted right 16 bits
 - [ ] Fixed: ctrl-r doesn't reload external changes for carts which are over compressed code capacity
 - ~~Fixed: false positives when detecting external changes for some older cart versions~~
 - [ ] Fixed: .p8.png carts saved with dense code (compressed size > raw size, including very small carts) stores junk
 - [ ] Fixed: error message duplication when loading future version of .p8.png carts
 - ~~Fixed: Illegal colours can enter spritesheet via serach-replace after setting with color()~~
 - [ ] Fixed: Preprocessor: "foo():a().x+=1" "a=b[1]c+=1"
 - ~~Fixed: hex numbers written with punyfont characters breaks syntax high-lighting~~
 - ~~Fixed: shift+- in sprite editor jumps too vertically when zoomed in~~
 - ~~Fixed: clicking a note in sfx editor creates a selection (-> backspace clears without moving rows)~~
 - [ ] Fixed: print() doesn't respect __tostring metatable method (regression)
 - [ ] Fixed: time() and btnp() speed changes after stopping program, typing a command and then resuming.
 - ~~Fixed: phantom drag & drop events sent to unused music channels causing them to occasionally unmute themselves~~
