### ISSUE TITLE
PICO-8 v0.2.1b compatiblity roadmap

### ISSUE THREAD

**Issue by samhocevar** [samhocevar/zepto8#23]
- [ ] Added: split(str,"") splits by single characters
 - ~~Updated: Tower of Archeos 1.1 via INSTALL GAMES~~
 - [ ] Fixed: print(num,x,y) always prints numbers num in hexidecimal
 - [ ] Fixed: .p8.png decoder can enter an infinite loop (caused exports to freeze on boot)
 - [ ] Fixed: Can't save screenshot/gif when running a BBS cart with illegal characters in title.
 - ~~Fixed: INSTALL_GAMES is broken~~
