### ISSUE TITLE
PICO-8 v0.2.2b compatiblity roadmap

### ISSUE THREAD

**Issue by samhocevar** [samhocevar/zepto8#29]
- [ ] Added: export foo.lua.png to get an image of the cartridge's source code
 - [ ] Added: Pause menu can be forced to appear by holding down pause for 300ms (even if program blocks it)
 - [ ] Added: extcmd("set_filename","foo") -- set the filename of the next screenshot or gif (can include %d)
 - [ ] Added: extcmd("set_title","foo") -- set window title (useful for exported binaries)
 - [ ] Added: Can toggle punyfont mode at command prompt w/ ctrl+p (useful for inspecting puny variable names!)
 - [ ] Changed: Default filename is /untitled.p8 instead of no filename (auto-increments to untitled_1.p8 etc.)
 - [ ] Changed: circ/oval that are not visible cost almost nothing, including circles that contain clipping region
 - [ ] Changed: filled circles/ovals that contain clipping region cost the same as the equivalent rectfill
 - ~~Changed: shift+enter in code editor only auto-completes block for DO, THEN, REPEAT or FUNCTION~~
 - [ ] Fixed: ?"\ac0" starts from d#0 instead of c0
 - [ ] Fixed: preprocessor regression when using string at end of ..= statement: if (true) then a..="b" end
 - [ ] Fixed: pressing L / R in paused menu is registered by running program after closing menu
 - [ ] Fixed: printing text in tall mode (?"\^ttall") via commandline can chop off bottom line before scrolling
 - ~~Fixed: drag-select text with cursor at bottom or top of screen scrolls too fast~~
 - [ ] Fixed: spurious stat(0) results when using yield() to exit frame instead of flip()
 - [ ] Fixed: line()/tline() sometimes draws pixels on opposite side of screen (0.2.2 regression)
 - [ ] Fixed: line()/tline() fails to draw lines that have x or y coordinates > 32767 pixels apart
 - [ ] Fixed: can peek() more than 8192 values in single call
 - [ ] Fixed: large fill circles (> radius 900) render incorrectly close to vertical center (32-bit builds, web)
 - [ ] Fixed: even-widthed filled ovals with midpoint < 0 is drawn off by 1
 - [ ] Fixed: black pixels in gif / map export not completely black
 - [ ] Fixed: map and spritesheet exporters do not respect current display palette and 0x5F36:0x8 (draw spr 0)
 - ~~Fixed: code editor: cursor position off by one when selecting character after glyph (0.2.2 regression)~~
 - ~~Fixed: code editor: tab names don't show up when 100% punyfont~~
 - ~~Fixed: import spritesheet.png failing under MacOS (0.2.2 regression)~~
 - ~~Fixed: export single sfx to .wav crashes when contains sfx instrument references~~
