### ISSUE TITLE
PICO-8 v0.2.4b compatiblity roadmap

### ISSUE THREAD

**Issue by samhocevar** [samhocevar/zepto8#37]
- [ ] Added: l in sprite sheet navigator to set loop start / end points (then q,w or a,z to navigate)
 - [ ] Added: ctrl-b in gfx editor to paste 2x2 original size ("paste big")
 - [ ] Added: DEL / backspace to clear selected region in gfx / map editors, and ctrl-x to cut
 - [ ] Added: aggressive_backups option in config.txt (off by default)
 - [ ] Added: transform_screen in config.txt to globally rotate / flip the video output
 - [ ] Added: stat(57) (boolean) true when music triggered by music() is playing or about to start
 - [ ] Changed: memset() faster than using peek4/poke4; now 2 cycles per byte at 8MHz (was 4)
 - [ ] Changed: "running at < 30fps" warning on boot now only for raspi builds, and w/ higher tolerance
 - [ ] Changed: Controller inputs are accepted even when PICO-8 is not the foreground application
 - [ ] Changed: Map can be located at 0x1000 .. 0x2f00 using poke(0x5f56, 0x11) .. poke(0x5f56,0x2f)
 - [ ] Changed: Dotty text mode is now "\^=" ("Stripey") instead of "\^." // #gunayawuho #klax #impossible
 - [ ] Fixed: (not confirmed) crash causing 0-byte .p8 when audio mixer is called during save / run
 - [ ] Fixed: preprocessor not counting comments as white space; should allow: ".. end--[[]]if .."
 - [ ] Fixed: pal(nil) behaving the same way as pal(0); should be same as pal() // broke #rtype-2
 - [ ] Fixed: note entry in sfx tracker is silent after running cartridge until pressing space to playback
 - [ ] Fixed: sub("abc", 4, 4) returns "c" (regression in 0.2.4)
 - [ ] Fixed: SPLORE cart update prompt does not appear when server replies too quickly (race condition)
 - [ ] Fixed: SPLORE cart update prompt only checks version once per session (can't refresh until it shows up)
 - [ ] Fixed: EXPORT command does not flatten includes when exporting to .p8.png / .p8.rom format
 - [ ] Fixed: EXPORT command discards source code changes since last run or load
 - [ ] Fixed: printing a one-off glyph using "\^." terminates the whole string when last byte is a zero
 - [ ] Fixed: Crash when loading a cart with fewer tabs, then creating a new tab and pasting.
 - [ ] Fixed: . command runs at 30fps even for a 60fps cart (-> _update60 is called twice, _draw once)
 - [ ] Fixed: Custom menu items become broken after suspending a cart, entering a lua command, and then resuming
 - [ ] Fixed: memset() with a non-zero value in shared memory region (0x1000..0x1fff) causes garbage corresponding mget() values
 - [ ] Fixed: web player/exports: ctrl-r causes erroneous "external changes reloaded" message and code corruption
