### ISSUE TITLE
PICO-8 v0.2.4c compatiblity roadmap

### ISSUE THREAD

**Issue by samhocevar** [samhocevar/zepto8#38]
- [ ] Added: save @url -- stores code + gfx as a URL if it can be encoded in 2040 characters
 - [ ] Added: html exports store volume/mute and other settings
 - [ ] Added: ctrl-g in sprite editor to toggle grid lines when zoomed in
 - [ ] Added: IMPORT -L FOO.PNG to import a 128x128 png to the cartridge label
 - [ ] Added: EXPORT -L FOO.PNG to export a 128x128 png of the cartridge label
 - [ ] Added: EXPORT -T FOO.P8.ROM to export only code section (t for tiny)
 - [ ] Added: ctrl-click on character count (bottom right) to see the twitter count (glyphs count as 2)
 - [ ] Added: __meta:*__ section to .p8 format -- can be used by external tools to store custom data
 - [ ] Added: extcmd("audio_rec") works from exported binaries, and with custom exported filenames
 - [ ] Added: read_controllers_in_background in config.txt (0 by default)
 - [ ] Added: periodic backups
 - [ ] Changed: .p8.rom files that are 0x3d00 bytes or less are loaded into code section
 - [ ] Changed: saved filenames can not include gylphs, or any of !"#$%&'()*+,-:;<=>?[\]^`{|}~
 - [ ] Fixed: can't drag and drop png into sprite editor
 - [ ] Fixed: binary exports: ctrl-r causes crash when there is no whitespace at end of source code
 - [ ] Fixed: Using -run switch to launch a cart that fails to run -> get stuck in boot screen.
 - [ ] Fixed: selection after ctrl-a reports length chars+1
 - [ ] Fixed: draw palette is not observed after changing colours using p8scii control characters
 - [ ] Fixed: music playback does not follow cursor after first pattern change (regression in 0.2.4b)
 - [ ] Fixed: transform_screen (config.txt) not observed by pause menus and other overlayed elements
 - [ ] Fixed: Double-clicking sfx thumbnail (in sfx overview screen) only works after playing music
 - [ ] Fixed: Pressing [a] to release looping sfx in sfx editor is broken
 - [ ] Fixed: sfx(46)..sfx(56) return -1 immediately after playing music but before host OS has called audio mixer
 - [ ] Fixed: Tokens counted as 2 instead of 1: ..= ^= >><= <<>=
 - [ ] Fixed: Negative number counted as 2 tokens instead of one when preceeded by: \ & | ^^ << >> >>> >>< <<>
 - [ ] Fixed: tostr(tbl) / print(tbl) acts like tostr(tbl, 1) when tbl has a metatable
 - [ ] Fixed: ?"\tx" does not advance to next tab stop
 - [ ] Fixed: ?"a\*5\nb" does not repeat newline 5 times
 - [ ] Fixed: exported label alpha is 0 for colour 0
