### ISSUE TITLE
PICO-8 v0.2.5 compatiblity roadmap

### ISSUE THREAD

**Issue by samhocevar** [samhocevar/zepto8#39]
- [ ] Added: Help topics. Use help command, or ctrl-u in code editor to get help on whatever is at the cursor.
 - [ ] Added: (html exports / bbs) downloadable .wav export using extcmd("audio_rec"), extcmd("audio_end")
 - [ ] Added: inext (to match next).  -> can do: for i,v in inext,tbl do ... end
 - [ ] Added: floating selection layer in map editor (solves various bugs and undo / selection issues)
 - [ ] Added: ~ can be used as xor instead of ^^ (same as Lua 5.3/5.4)
 - [ ] Added: When running a program locally, ls() can now take a directory name; use stat(124) to get pwd
 - [ ] Added: Variable width P8SCII fonts
 - [ ] Added: ctrl-click on compressed capcity (bottom right) to get realtime updates of compressed size in bytes
 - [ ] Added: export -t @clip to get a hexdump of compressed code section copied to clipboard
 - [ ] Added: pico8 -scancodes and map_scancodes (config.txt) for manually mapping keys to alternative scancodes
 - [ ] Added: sub(str,pos,pos) can be written as str[pos]
 - [ ] Changed: host_framerate_control 1 (config.txt) now means "let PICO-8 decide"; is disabled for Mac/Win/Linux
 - [ ] Changed: in map editor, pan with cursor keys when nothing is selected
 - [ ] Changed: use scancodes for sfx navigation (US:-=_+) and spd change (US:,.<>) to avoid azerty collisions
 - [ ] Changed: gfx_grid_lines in config.txt is taken to be a colour for the grid lines (16 for black)
 - [ ] Changed: can ctrl-h in gfx editor to toggle hex mode (sprite index shown in hex; map vals shown)
 - [ ] Changed: '-' allowed in filenames when not first character
 - [ ] Changed: linux builds use libcurl.so for bbs requests, or drops down to wget on failure to dlopen
 - [ ] Changed: increased maximum gif len for web exports to 30 seconds
 - [ ] Changed: peek/poke can now read/write up to 32767 values (was 8192)
 - [ ] Changed: web player default gif len is 16 seconds (was 8)
 - [ ] Changed: sub(str, pos, nil) returns whole string (pre-0.2.4 behaviour). For single chars, can now use str[pos].
 - [ ] Fixed: Windows reserved filenames (lpt1, com1 etc) are accepted
 - [ ] Fixed: Nested coroutines unexpectedly end when interrupted by reaching end of frame
 - [ ] Fixed: print() colour is remapped twice when set in parameter // pal(6,7) pal(7,8) print("white",6)
 - [ ] Fixed: circ() breaks on 32-bit builds, with radius > 1024
 - [ ] Fixed: ctrl-c to copy commandline error message does not encode glyphs as unicode
 - [ ] Fixed: LS command not resolving relative paths
 - [ ] Fixed: twitter char count for chr(127) ○ should be 2 (was 1) and chr(149) ˇ should be 1 (was 2)
 - [ ] Fixed: colour parameter not converted from string in rect, rectfill, pset (regression from 0.2.2)
 - [ ] Fixed: ord("foo", 1, 0) returns "too many ord results" -- should return nothing
 - [ ] Fixed: save @url includes ?g= when no gfx data (is redundant)
 - [ ] Fixed: (web export) html pause button does not show up as btnp(6) / btn(6)
 - [ ] Fixed: (web export) codo_textarea triggering Mac accent character selector even when cart doesn't use clipboard
 - [ ] Fixed: save @url failing when encoded length is > 2000 chars long instead of > 2040 charss
 - [ ] Fixed: can enter an illegal note (e-5) in sfx editor
