### ISSUE TITLE
PICO-8 v0.2.5c compatiblity roadmap

### ISSUE THREAD

**Issue by samhocevar** [samhocevar/zepto8#40]
- [ ] Added: set out of range return value for sget, mget, pget: poke (0x5f36,0x10) and set at 0x5f59..0x5f5b
 - [ ] Changed: rnd(str) no longer returns a random char from strings (breaks existing carts using e.g. rnd"5")
 - [ ] Changed: html exports default to 75% volume instead of 100%
 - [ ] Fixed: extcmd("audio_rec"), extcmd("audio_end") not working in html exports
 - [ ] Fixed: drag & drop (via serial 0x802) not responding to dropped file in html exports
 - [ ] Fixed: (again) can enter an illegal note (e-5) in sfx editor
 - [ ] Fixed: dir() missing during runtime (alias for ls)
 - [ ] Fixed: some mistakes in help text (outdated sub() description, yield misspelling)
