### ISSUE TITLE
PICO-8 v0.2.5d compatiblity roadmap

### ISSUE THREAD

**Issue by samhocevar** [samhocevar/zepto8#41]
- [ ] Added: tline(bits) to set number of bits used for fractional part of mx,my,mdx,mdy (13 by default)
 - [ ] Added: ctrl+mousewheel to scroll code horizontally
 - [ ] Added: current bbs cartridge id shown in window title (config.txt show_cart_id_in_title to disable)
 - [ ] Added: poke(0x5f36, (@0x5f36)|0x80) to enable character wrap by default when printing
 - [ ] Added: blit_method in config.txt  // Can use a software blitter by default (slower but more reliable)
 - [ ] Added: reminder when re-locating sprites that only the top half of map is altered by default
 - [ ] Added: draw boot sound as note glyphs on startup when sound is off
 - [ ] Changed: print() returns both max(cur_x), max(cur_y) and includes non-printed characters (e.g. tabs)
 - [ ] Changed: extcmd("folder") and extcmd("set_title", "foo") can now be used from bbs carts
 - [ ] Changed: Indexing a string out of range returns nil (was "")
 - [ ] Changed: Replaced most of pre-processor with Lua parser modifications based on z8lua (fixes various edge cases)
 - [ ] Changed: "a[foo()] += 1" only evaluates foo() once
 - [ ] Changed: out-of-bound tile values can be drawn using map(), tline()
 - [ ] Changed: extcmd("audio_rec") can record a maximum of 8 minutes (was no limit previously)
 - [ ] Changed: Rate limits are now per-minute: 10MB of log wries, 64 different files, 10 extcmd("folder")'s)
 - [ ] Fixed: Infinite tokens hack (was caused by now-replaced pre-processor)
 - [ ] Fixed: Only 4 controllers mapped to 0x5f00+76
 - [ ] Fixed: h toggles hexadecimal mode in gfx editor (should be ctrl-h -- h is to flip sprite horizontally)
 - [ ] Fixed: out-of-bounds value doesn't respect custom map size
 - [ ] Fixed: cutting or clearing a selection of sprites does not also clear the sprite flags
 - [ ] Fixed: P8SCII repeat-character command fails on zero repetions; ?"a\*0bc" should print "ac", not "abc"
 - [ ] Fixed: pxa code compression inefficient when >= 32k matching triplets (typically "000")
 - [ ] Fixed: print() return value max(cur_x) returns 0 when max(cur_x < 0)
 - [ ] Fixed: holding menu button to force pause menu to open broken in binary exports
 - [ ] Fixed: copying / pasting in commandline doesn't respect punyfont character encoding
 - [ ] Fixed: (Manual) Steps 1 & 2 on how to move sprites in the map are in the wrong order
 - [ ] Fixed: Unhelpful / no error messages when the wrong format for HELP is used
