### ISSUE TITLE
PICO-8 v0.2.5f compatiblity roadmap

### ISSUE THREAD

**Issue by samhocevar** [samhocevar/zepto8#43]
- [ ] Added: CONFIG DRAW_TABS 1 to show tab characters in code editor (previously required editing config.txt)
 - [ ] Changed: tokenizer recognises long comments / string using [=*[ ]=*] e.g. [==[ long string ]==]
 - [ ] Changed: Nested long comments and strings no longer allowed
 - [ ] Changed: x % 0 gives 0 (was x)
 - [ ] Optimised: software blitter now faster when using PocketCHIP, windowed raspi or blit_method 1
 - [ ] Fixed: infinite tokens exploit introduced in 0.2.5d (due to pre-processor changes)
 - [ ] Fixed: >>>= operator is a NOP (bug introduced in 0.2.5d)
 - [ ] Fixed: (raspi 32-bit) window not visible under Gameforce Chi / EmuELEC -- bug introduced in 0.2.5e
 - [ ] Fixed: fixed: s="x".."=" counts as 4 tokens instead of 5
 - [ ] Fixed: Running a cartridge containing _meta_ data prints a memory allocation warning to stdout
 - [ ] Fixed: Code compressing to >= 32k reports size as (compressed_size & 0x7fff) resulting in corruped exports
 - [ ] Fixed: stat(54) loops when left-most channel is looping (should return total played ticks on current pattern)
 - [ ] Fixed: extcmd("audio_rec") maximum length is 2 minutes (meant to be 8 -- and now only applies to web)
 - [ ] Fixed: Frog Home crashes because of (now unsupported) "local x+=.." form. // INSTALL_GAMES for fixed version
 - [ ] Fixed: Starting P8SCII font height affects total line height even when no characters are printed in that font
