### ISSUE TITLE
Architecture roadmap

### ISSUE THREAD

**Issue by samhocevar** [samhocevar/zepto8#9]
### Code quality
 - [ ] Refactor logging so as not to rely on `lol::msg::xxx` everywhere
 - [ ] Get rid of `lol::File`
 - [ ] Refactor `lol::PixelFormat`
 - [ ] In general, track down all uses of `<lol/engine.h>`

### libretro
 - [ ] List all the API entry points we should use
 - [ ] Make the core not rely on Lol Engine or SDL if not required
